[package]
name = "server-test"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
actix-session = { version = "0.10", features = ["cookie-session"] }
actix-files = "0.6"
actix-web-lab = "0.24"
async-stream = "0.3"
tracing = "0.1.30"
